# conda environment description file for SoG-bloomcast package development environment
#
# Create a conda environment in which the `bloomcast` command can be run
# with:
#
#   $ conda env create -f SOG-Bloomcast-Ensemble/environment.yml
#   $ conda activate bloomcast
#   (bloomcast)$ python -m pip install --editable SOG
#   (bloomcast)$ python -m pip install --editable SOG-Bloomcast-Ensemble
#
# The environment will also include all the tools used to develop,
# test, and document the SoG-bloomcast package.
#
# See the requirements.txt file for an exhaustive list of all the
# packages installed in the environment and their versions used in
# recent development.

name: bloomcast

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - beautifulsoup4
  - colander<2
  - jupyterlab
  - cliff
  - matplotlib
  - numpy
  - pip
  - python=3.12
  - pyyaml
  - requests

  # For unit tests
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme
