name: bloomcast
dependencies:
- docutils=0.12=py34_0
- fontconfig=2.11.1=3
- freetype=2.5.2=0
- jinja2=2.7.3=py34_1
- libpng=1.5.13=1
- libxml2=2.9.0=0
- markupsafe=0.23=py34_0
- matplotlib=1.4.3=np19py34_1
- numpy=1.9.2=py34_0
- openssl=1.0.1k=1
- pip=6.1.1=py34_0
- py=1.4.26=py34_0
- pygments=2.0.2=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.3=py34_1
- pytest=2.7.0=py34_0
- python=3.4.3=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.2=py34_0
- pyyaml=3.11=py34_0
- qt=4.8.6=1
- readline=6.2=2
- requests=2.6.0=py34_0
- setuptools=15.0=py34_0
- sip=4.16.5=py34_0
- six=1.9.0=py34_0
- sphinx=1.2.3=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- xz=5.0.5=0
- yaml=0.1.4=0
- zlib=1.2.8=0
- pip:
  - arrow==0.5.4
  - beautifulsoup4==4.3.2
  - cliff==1.11.0
  - cmd2==0.6.8
  - colander==1.0
  - iso8601==0.1.10
  - mako==1.0.1
  - nose==1.3.4
  - pathlib==1.0.1
  - pbr==0.10.8
  - prettytable==0.7.2
  - sog-bloomcast (/home/dlatornell/SOG-projects/SoG-bloomcast-ensemble)==3.1.dev0
  - sogcommand (/home/dlatornell/SOG-projects/SOG)==1.3.3
  - sphinx-bootstrap-theme==0.4.5
  - stevedore==1.4.0
  - translationstring==1.3

