name: bloomcast
dependencies:
- beautifulsoup4
- colander
- mako
- matplotlib
- notebook
- numpy
- pip
- pytest
- python=3
- pyyaml
- requests
- six
- sphinx
- pip:
  - arrow
  - cliff
  - sphinx-bootstrap-theme

