# conda environment description file for SOG-Bloomcast-Ensemble package development environment
#
# Create a conda environment in which the `bloomcast` command can be run
# with:
#
#   $ mamba env create -f SOG-Bloomcast-Ensemble/envs/environment-dev.yaml
#   $ mamba activate bloomcast-dev
#   (bloomcast-dev)$ python -m pip install --editable SOG
#   (bloomcast-dev)$ python -m pip install --editable SOG-Bloomcast-Ensemble
#
# The environment will also include all the tools used to develop,
# test, and document the SOG-Bloomcast-Ensemble package.
#
# See the envs/requirements.txt file for an exhaustive list of all the
# packages installed in the environment and their versions used in
# recent development.

name: bloomcast-dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - beautifulsoup4
  - colander<2
  - jupyterlab
  - cliff
  - matplotlib
  - numpy
  - pip
  - python=3.13
  - pyyaml
  - requests

  # For capturing email messages during testing
  - aiosmtpd

  # For coding style, repo QA, and package management
  - black
  - hatch
  - pre-commit

  # For unit tests and coverage monitoring
  - pytest
  - pytest-cov
  - pytest-randomly

  # For documentation
  - sphinx=8.1.3
  - sphinx-rtd-theme=3.0.0
