# conda environment description file for SOG-Bloomcast-Ensemble package testing environment
#
# Creates a conda environment in which the SOG-Bloomcast-Ensemble package unit tests and
# coverage analysis can be run.
# Primarily intended to create a conda env for use in a GitHub Actions workflow.

name: bloomcast-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - beautifulsoup4
  - colander<2
  - jupyterlab
  - cliff
  - matplotlib
  - numpy
  - pip
  - pyyaml
  - requests

  # For unit tests and coverage monitoring
  - pytest
  - pytest-cov
  - pytest-randomly

  - pip:
    # Install theSOG and SOG-Bloomcast-Ensemble packages in editable mode
    - --editable git+https://github.com/SalishSeaCast/SOG.git#egg=SOGcommand
    - --editable ../
