# SoG bloomcast configuration file

get_forcing_data: True
run_SOG: True

SOG_executable: ../../SOG-code-bloomcast/SOG
html_results: ../bloomcast/html

ensemble:
  max_concurrent_jobs: 32
  base_infile: 2014_bloomcast_infile.yaml
  start_year: 1981   # 1st bloomcast year
  end_year: 2010     # last bloomcast year
  forcing_data_file_roots:
    wind: ../../SOG-forcing/wind/2yr_chunks/SH_pp_08Feb2014.dat
    air_temperature: ../../SOG-forcing/met/2yr_chunks/YVRhistAT
    cloud_fraction: ../../SOG-forcing/met/2yr_chunks/YVRhistCF
    relative_humidity: ../../SOG-forcing/met/2yr_chunks/YVRhistHum
    major_river: ../../SOG-forcing/rivers/2yr_chunks/Fraser_total_10Jul2012.dat
    minor_river: ../../SOG-forcing/rivers/2yr_chunks/Englishman_total_21Aug2012.dat

climate:
  url: http://climate.weather.gc.ca/climateData/bulkdata_e.html
  params:
    timeframe: 1        # Daily
    format: xml
  meteo:
    station_id: 51442   # YVR
    quantities:
      - air_temperature
      - relative_humidity
      - cloud_fraction
    cloud_fraction_mapping: cloud_fraction_mapping.yaml  # file containing mapping
  wind:
    station_id: 6831    # Sandheads

rivers:
  disclaimer_url: http://www.wateroffice.ec.gc.ca/include/disclaimer.php
  accept_disclaimer:
    disclaimer_action: I Agree
  data_url: http://www.wateroffice.ec.gc.ca/graph/graph_e.html
  params:
    mode: text
    prm1: 6              # discharge
  major:
    station_id: 08MF005  # Fraser River at Hope
  minor:
    station_id: 08HB002  # Englishman River at Parksville

logging:
  debug: True
  bloomcast_log_filename: bloomcast.log
  bloom_date_log_filename: bloom_date_evolution.log
  toaddrs:
    - sallen@eos.ubc.ca
  # Run "python -m smtpd -n -c DebuggingServer localhost:1025" to
  # capture email messages for testing
  use_test_smtpd: False

results_dir: /home/sallen/public_html/SoG-bloomcast
