# SoG bloomcast configuration file

get_forcing_data: True
run_SOG: True

SOG_executable: ../../SOG-code-bloomcast/SOG

ensemble:
  max_concurrent_jobs: 32
  base_infile: 2017_bloomcast_infile.yaml
  start_year: 1981   # 1st bloomcast year
  end_year: 2010     # last bloomcast year
  forcing_data_file_roots:
    wind: ../../SOG-forcing/wind/2yr_chunks/SH_pp_08Feb2014.dat
    air_temperature: ../../SOG-forcing/met/2yr_chunks/YVRhistAT
    cloud_fraction: ../../SOG-forcing/met/2yr_chunks/YVRhistCF
    relative_humidity: ../../SOG-forcing/met/2yr_chunks/YVRhistHum
    major_river: ../../SOG-forcing/rivers/2yr_chunks/Fraser_total_10Jul2012.dat
    minor_river: ../../SOG-forcing/rivers/2yr_chunks/Englishman_total_21Aug2012.dat

climate:
  url: http://climate.weather.gc.ca/climate_data/bulk_data_e.html
  params:
    timeframe: 1        # Daily
    format: xml
  meteo:
    station_id: 51442   # YVR
    quantities:
      - air_temperature
      - relative_humidity
      - cloud_fraction
    cloud_fraction_mapping: cloud_fraction_mapping.yaml  # file containing mapping
  wind:
    station_id: 6831    # Sandheads

rivers:
  data_url: http://wateroffice.ec.gc.ca/report/report_e.html
  disclaimer_cookie:
    disclaimer: agree
  params:
    type: realTime
    mode: Table
    prm1: 47              # discharge
    prm2: -1
  major:
    station_id: 08MF005  # Fraser River at Hope
  minor:
    station_id: 08HB002  # Englishman River at Parksville

logging:
  bloomcast_log_filename: bloomcast.log
  bloom_date_log_filename: bloom_date_evolution.log
  toaddrs:
    - sallen@eos.ubc.ca
  # Run "python -m smtpd -n -c DebuggingServer localhost:1025" to
  # capture email messages for testing
  use_test_smtpd: False

results:
  site_repo_url: https://bitbucket.org/salishsea/salishsea-site
  site_bloomcast_path: site/bloomcast
  site_plots_path: site/_static/bloomcast/spring_diatoms
  www_path: www
  templates_path: www/templates
  template_stem: 'spring_diatoms'
  push_to_web: True
  server_path: skookum-bloomcast:/var/www/html
